#!/bin/bash

set -uo pipefail

die() {
  echo >&2 "$1"
  exit 1
}

usage() {
  echo -e "Usage: $0 <deb file> <output dir>" >&2
  exit 2
}

extract() {
  local deb
  local out
  local tmp
  deb=$(readlink -f "$1")
  out="$2"
  tmp=$(mktemp -d)

  if [ ! -d "$out" ]; then
    mkdir "$out"
  fi
  cd "$tmp"
  ar xv "$deb" || die "ar failed"
  if [ -f "data.tar.zst" ]; then
    tar -I zstd -xf data.tar.* || die "tar failed"
  else
    tar xf data.tar.* || die "tar failed"
  fi
  cd -

  cp -rP "${tmp}"/lib/*/* "$out" 2>/dev/null ||
    cp -rP "${tmp}"/lib32/* "$out" 2>/dev/null ||
    cp -rP "${tmp}"/usr/lib/*/* "$out" 2>/dev/null ||
    cp -rP "${tmp}"/usr/lib/debug/lib/*/* "$out" 2>/dev/null ||
    cp -rP "${tmp}"/usr/lib/debug/lib32/* "$out" 2>/dev/null ||
    cp -rP "${tmp}"/usr/lib/debug/.build-id "$out" 2>/dev/null ||
    die "Failed to save. Check it manually ${tmp}"

  rm -rf "$tmp"
}

if [[ $# -ne 2 ]]; then
  usage
fi

cd "$(dirname "$0")"

extract "$1" "$2"
